sprint-1/step-2
Aigelov/react-burger pull request #2
Opened 2021-06-24 04:40 UTC by Aigelov

2021-06-24 10:02 UTC, SmilingJey requested changes
Здравствуйте!

Отличная работа! Приложение отлично декомпозировано на компоненты, правильно используются компоненты из библиотеки, код хорошо оформлен, правильно рализованы попапы с помощью портала и работает закрытие по ESC и оверлею. 
Но есть несколько замечаний:

**Нужно исправить:**

- не у всех компонентов, в которых есть провсы, описаны propTypes, нужно описать везде

- при маленькой высоте экрана кнопка оформления заказа скрывается за пределами экрана и на неё невозможно нажать, такого происходить не должно

- магическое значение 27 нужно вынести в именованную константу

**Места, в которых можно улучшить проект:**

- во многих компонентах дублируется описание PropTypes ингредиента
Лучше вынести его в отдельный файл (можно создать файл prop-types.js в корне src ) и переиспользовать описание пропсов ингрединта, а не дублировать

- есть лишние обертки <>, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков

- не нужно создавать три компонента - BurgerIngredientsBunTab BurgerIngredientsMainTab BurgerIngredientsSauceTab - достаточно одного, а тип, по которому производится фильтрация и title передавать как пропсы

- у запроса к серверу добавьте проверку res.ok.

- вызывать скрытие индикатора загрузки лучше в блоке finally, а не дублировать в then и catch

- закрытие по оверлею можно реализовать просто как события клика на оверлей, в не на document

2021-06-24 10:02 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.jsx
> +    <>
**Можно лучше**
эта обёртка <> лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например
```
<>
  <div>.....</div>
  <div>.....</div>
</>
```
https://ru.reactjs.org/docs/fragments.html

2021-06-24 10:02 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.jsx
> +export const BurgerConstructor = ({ ingredients }) => {
**Надо исправить**

нужно описать propTypes для этого компонента

2021-06-24 10:02 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.jsx
> +        <span className={bottomStyles}>
**Надо исправить**

при маленькой высоте экрана кнопка скрывается за пределами экрана и на неё невозможно нажать, такого происходить не должно

![Screenshot_36](https://user-images.githubusercontent.com/9317133/123238600-467c0980-d4e7-11eb-8dfe-b307a7a47888.png)

2021-06-24 10:02 UTC, SmilingJey commented on src/components/burger-constructor-item/burger-constructor-item.jsx
> +    <>
**Можно лучше**
эта обёртка <> лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например
```
<>
  <div>.....</div>
  <div>.....</div>
</>
```
https://ru.reactjs.org/docs/fragments.html

2021-06-24 10:02 UTC, SmilingJey commented on src/components/burger-ingredients/burger-ingredients.jsx
> +export const BurgerIngredients = ({ ingredients }) => {
**Надо исправить**

для этого компонента так же нужно описать propTypes

2021-06-24 10:02 UTC, SmilingJey commented on src/components/burger-ingredients-bun-tab/burger-ingredients-bun-tab.jsx
> +export const BurgerIngredientsBunTab = ({
**Надо исправить**

для этого компонента так же нужно описать propTypes

2021-06-24 10:02 UTC, SmilingJey commented on src/components/burger-ingredients-bun-tab/burger-ingredients-bun-tab.jsx
**Можно лучше**

не дублируйте компоненты, не нужно создавать три компонента - BurgerIngredientsBunTab BurgerIngredientsMainTab  BurgerIngredientsSauceTab - достаточно одного, а тип, по которому производится фильтрация и title передавать как пропсы

2021-06-24 10:02 UTC, SmilingJey commented on src/components/burger-ingredients-main-tab/burger-ingredients-main-tab.jsx
> +export const BurgerIngredientsMainTab = ({
**Надо исправить**

для этого компонента нужно так же описать propTypes

2021-06-24 10:02 UTC, SmilingJey commented on src/components/burger-ingredients-sauce-tab/burger-ingredients-sauce-tab.jsx
> +export const BurgerIngredientsSauceTab = ({
**Надо исправить**

для этого компонента нужно так же описать propTypes

2021-06-24 10:02 UTC, SmilingJey commented on src/components/main/main.jsx
> +export const Main = ({ ingredients }) => {
**Надо испарвить**

для этого компонента так же нужно описать propTypes

2021-06-24 10:02 UTC, SmilingJey commented on src/components/modal/modal.jsx
> +      if (keyCode === 27) {
**Надо исправить**

магическое значение 27 нужно вынести в именованную константу

2021-06-24 10:02 UTC, SmilingJey commented on src/components/modal/modal.jsx
> +    document.addEventListener("click", clickHandler, false);
**Можно лучше:**

закрытие по оверлею можно реализовать просто как события клика на оверлей, в не на document

2021-06-24 10:02 UTC, SmilingJey commented on src/components/ingredient-details-item/ingredient-details-item.jsx
> +export const IngredientDetailsItem = ({ title, info }) => {
Надо исправить

для этого компонента так же нужно описать propTypes

2021-06-24 10:02 UTC, SmilingJey commented on src/components/modal/modal.jsx
> +export const Modal = ({ children, header, onClose }) => {
**Надо исправить**

для этого компонента так же нужно описать propTypes

2021-06-24 10:02 UTC, SmilingJey commented on src/components/app.tsx
> +        setLoading(false);
**Можно лучше**

вызывать скрытие индикатора загрузки лучше в блоке finally, а не дублировать в then и catch
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

2021-06-24 10:02 UTC, SmilingJey commented on src/components/app.tsx
> +        const response = await res.json();
**Можно лучше**
Добавьте проверку, что произошла ошибка - res.ok. 
`res => res.ok ? res.json() : Promise.reject(res)`

Иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой мы не попадем в catch, а попытаемся отрисовать данные, хотя они не пришли, в итоге вместо отображения сообщения об ошибке загрузки данных на попытке отрисовки несуществующих данных упадет все приложение

https://learn.javascript.ru/fetch
https://developer.mozilla.org/en-US/docs/Web/API/Response/ok

2021-06-24 12:50 UTC, Aigelov commented on src/components/modal/modal.jsx
> +    document.addEventListener("click", clickHandler, false);
В компоненте Modal убрал modalRef и всё что с ним связано, это eventListener click, clickHandler
В компонент ModalOverlay передал пропс onClose метод
В компоненте ModalOverlay для div добавил onClick={onClose}
Теперь при нажатии в любом месте закрывается модальное окно, даже при нажатии внутр модального окна, такое поведение мне не понравилось, ведь по хорошему при нажатии внутр модального окна, модальное окно не должно закрываться, в связи с этим оставил исправно рабочую версию кода

2021-06-24 12:51 UTC, Aigelov commented on src/components/app.tsx
> +        const response = await res.json();
Отработал практически по всем замечаниям, кроме одного пункта, где оставил комментарий

2021-06-25 06:10 UTC, SmilingJey commented on src/components/modal/modal.jsx
> +    document.addEventListener("click", clickHandler, false);
Можно было попробовать добавить такую проверку

```
if (event.target === event.currentTarget) {
      onClose();
    }
```

тогда клик бы срабатывал только по самому оверлею

2021-06-25 06:35 UTC, SmilingJey approved these changes
Отлично, замечания исправлены, но не забудьте поправить оставшееся замечание по propTypes - указывать isRequired у описания пропсов

Успехов в дальнейшем обучении!

2021-06-25 06:35 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.jsx
> +  ingredients: PropTypes.arrayOf(PropTypes.shape(BurgerIngredientPropTypes)),
**здесь и в других местах** - добавьте isRequired к описанию пропса, без указания этого пропс можно вообще не передать и предупреждения не будет

```
BurgerConstructor.propTypes = {
  ingredients: PropTypes.arrayOf(PropTypes.shape(BurgerIngredientPropTypes)).isRequired,
};
```

2021-06-27 09:07 UTC, merged